<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
        <Nullable>enable</Nullable>
        <UseUwp>true</UseUwp>
        <Platforms>x86;x64;arm64</Platforms>
        <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <DefaultLanguage>en-US</DefaultLanguage>
        <PublishAot>true</PublishAot>
        <PublishProfile>win-$(Platform).pubxml</PublishProfile>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
        <EnableTypeInfoReflection>false</EnableTypeInfoReflection>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <EnableMsixTooling>true</EnableMsixTooling>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="Microsoft.UI.Xaml" Version="2.8.7" />
      <PackageReference Include="Win2D.uwp" Version="1.28.3" />
    </ItemGroup>
</Project>